[features]
seeds = false
skip-lint = false

[programs.localnet]
liquidity_pool = "G7G2o7vaMvacSkMENdBjqjECjpK3USBpDmSzpDo6JWrf"

[programs.devnet]
liquidity_pool = "G7G2o7vaMvacSkMENdBjqjECjpK3USBpDmSzpDo6JWrf"

[programs.mainnet]
liquidity_pool = "G7G2o7vaMvacSkMENdBjqjECjpK3USBpDmSzpDo6JWrf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"