[workspace]
members = [
    "programs/*",
]
resolver = "2"

[profile.release]
overflow-checks = false
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1